"""TIAS data model: TradeIntelligence dataclass representing one captured trade."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class TradeIntelligence:
    """Complete captured context for one closed trade.

    Populated by TradeContextCollector at trade close time.
    Group F (ds_*) fields are filled by DeepSeek analysis in Phase 2.

    Groups:
        A: Trade outcome — always populated from callback record.
        B: Entry decision context — from DB queries (may be None).
        C: Market conditions at close — from regime detector / altdata (may be None).
        D: Technical indicators at close — from TACache (may be None).
        E: Mode4 profit tracking data — from ProfitSniper (may be None).
        F: DeepSeek analysis — Phase 2 only, always None in Phase 1.
        G: Metadata timestamps.
    """

    # --- Group A: Trade Outcome (always populated) ---
    symbol: str
    direction: str
    strategy_name: str
    strategy_category: str
    source: str
    closed_by: str
    entry_price: float
    exit_price: float
    pnl_pct: float
    pnl_usd: float
    win: bool
    hold_seconds: float
    # T2-3 (2026-05-12) — exchange mode at trade close. Authoritative
    # source is ``Transformer.current_mode`` at the moment of
    # ``TradeCoordinator.on_trade_closed``. Pre-fix, the trade_intelligence
    # column existed (schema v32) and defaulted to 'shadow' for every row
    # because the collector never populated it — bybit_demo trades were
    # silently mislabeled as shadow, poisoning the brain's learning loop.
    # Default empty string here so the asdict-based repo INSERT picks up
    # the column; the coordinator passes the real mode via the record dict.
    exchange_mode: str = ""

    # --- Group B: Entry Decision Context ---
    leverage: Optional[float] = None
    position_size_usd: Optional[float] = None
    claude_thesis: Optional[str] = None
    claude_signal: Optional[str] = None
    claude_confidence: Optional[float] = None
    entry_score: Optional[float] = None
    ensemble_votes: Optional[str] = None
    # Layer 2 Defect 6 (2026-05-22) — numeric per-trade counts of strategies
    # that supported / opposed the trade direction at decision time. Sourced
    # from EnsembleStateCache.get_current_consensus(symbol) at register_trade
    # time and propagated via the close-record dict. Joinable to trade_log
    # outcomes for Layer 3 strategy weighting and Layer 4 herding analysis.
    # NULL when the cache lookup returns no record (e.g., trade opened via a
    # path that bypassed the ensemble — none in current production).
    supporting_count: Optional[int] = None
    opposing_count: Optional[int] = None
    # Layer 2 Defect 1 (2026-05-22) — per-cycle-per-symbol join key.
    # Generated by EnsembleVoter.vote as f"{cycle_iso}_{symbol}"; carried
    # forward via TradeState + the close-record dict so a trade's outcome
    # joins back to its per-strategy vote breakdown in the ensemble_votes
    # table: ``ON ensemble_votes.setup_id = trade_intelligence.setup_id``.
    # None when the trade opened via a path that bypassed the ensemble.
    setup_id: Optional[str] = None
    # Entry-time market snapshot — captured at order placement via strategy_worker
    entry_regime: Optional[str] = None
    entry_rsi: Optional[float] = None
    entry_macd_hist: Optional[float] = None
    entry_atr_pct: Optional[float] = None

    # --- Group C: Market Conditions at Close ---
    regime: Optional[str] = None
    fear_greed_value: Optional[int] = None
    fear_greed_label: Optional[str] = None
    regime_verified: int = 0  # 1 = per-coin regime confirmed, 0 = possibly global fallback

    # --- Group D: Technical Indicators at Close ---
    rsi: Optional[float] = None
    macd_hist: Optional[float] = None
    macd_signal: Optional[float] = None
    bollinger_pct: Optional[float] = None
    ema_20: Optional[float] = None
    ema_50: Optional[float] = None
    stochastic_k: Optional[float] = None
    stochastic_d: Optional[float] = None
    adx: Optional[float] = None
    atr_value: Optional[float] = None
    atr_pct: Optional[float] = None
    volume_ratio: Optional[float] = None
    price_vs_vwap: Optional[float] = None

    # --- Group E: Mode4 Profit Tracking Data ---
    m4_peak_pnl_pct: Optional[float] = None
    m4_ticks_in_profit: Optional[int] = None
    m4_ticks_total: Optional[int] = None
    m4_composite_score: Optional[float] = None
    m4_hurst_value: Optional[float] = None
    m4_momentum_decay: Optional[float] = None
    m4_extension_score: Optional[float] = None
    m4_ev_ratio: Optional[float] = None
    m4_volume_div_score: Optional[float] = None

    # --- Group APEX: Optimization tracking (Phase 3 feedback loop) ---
    apex_optimized: bool = False
    apex_flipped: bool = False
    apex_original_direction: Optional[str] = None
    apex_final_direction: Optional[str] = None
    apex_original_sl: Optional[float] = None
    apex_final_sl: Optional[float] = None
    apex_original_tp: Optional[float] = None
    apex_final_tp: Optional[float] = None
    apex_original_size: Optional[float] = None
    apex_final_size: Optional[float] = None
    apex_confidence: Optional[float] = None
    apex_tp_mode: Optional[str] = None
    apex_reasoning: Optional[str] = None
    apex_model: Optional[str] = None
    apex_response_ms: Optional[int] = None
    apex_cost_usd: Optional[float] = None
    gate_adjustments: Optional[str] = None
    apex_tp_fill_rate: Optional[float] = None  # % of intended TP actually captured

    # --- Group F: DeepSeek Analysis (Phase 2 — always None in Phase 1) ---
    ds_why: Optional[str] = None
    ds_what_worked: Optional[str] = None
    ds_what_failed: Optional[str] = None
    ds_lessons: Optional[str] = None
    ds_category: Optional[str] = None
    ds_confidence: Optional[float] = None
    ds_analyzed_at: Optional[str] = None
    # Phase 2 — actionable analysis fields
    ds_correct_direction: Optional[str] = None
    ds_what_should_done: Optional[str] = None
    ds_how_to_exploit: Optional[str] = None
    ds_optimal_direction: Optional[str] = None
    ds_optimal_sl_pct: Optional[float] = None
    ds_optimal_tp_pct: Optional[float] = None
    ds_optimal_size_usd: Optional[float] = None
    ds_optimal_leverage: Optional[int] = None
    # Phase 2 — API response metadata
    ds_raw_response: Optional[str] = None
    ds_response_time_ms: Optional[int] = None
    ds_input_tokens: Optional[int] = None
    ds_output_tokens: Optional[int] = None
    ds_cost_usd: Optional[float] = None
    ds_model: Optional[str] = None
    analysis_version: Optional[int] = None

    # --- Group G: Metadata ---
    trade_id: str = ""
    trade_closed_at: str = ""
    captured_at: str = ""
