"""Signal pipeline data types for the 4-layer architecture."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from src.core.types import Side


@dataclass
class RawSignal:
    """Layer 1 output: a strategy detected a potential trade setup."""
    strategy_name: str
    strategy_category: str
    symbol: str
    direction: Side
    entry_price: float
    suggested_stop_loss: float
    suggested_take_profit: float
    timeframe: str
    conditions_met: dict = field(default_factory=dict)
    conditions_strength: dict = field(default_factory=dict)
    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "strategy_name": self.strategy_name,
            "strategy_category": self.strategy_category,
            "symbol": self.symbol,
            "direction": self.direction.value,
            "entry_price": self.entry_price,
            "suggested_stop_loss": self.suggested_stop_loss,
            "suggested_take_profit": self.suggested_take_profit,
            "timeframe": self.timeframe,
            "conditions_met": self.conditions_met,
            "conditions_strength": self.conditions_strength,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class ScoredSetup:
    """Layer 2 output: a scored and ranked trade setup."""
    raw_signal: RawSignal
    base_score: float
    confluence_score: float
    context_score: float
    quality_score: float
    total_score: float
    grade: str
    scoring_details: dict = field(default_factory=dict)
    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "raw_signal": self.raw_signal.to_dict(),
            "base_score": round(self.base_score, 2),
            "confluence_score": round(self.confluence_score, 2),
            "context_score": round(self.context_score, 2),
            "quality_score": round(self.quality_score, 2),
            "total_score": round(self.total_score, 2),
            "grade": self.grade,
            "scoring_details": self.scoring_details,
        }


@dataclass
class EnsembleVote:
    """A single strategy's vote on a setup."""
    strategy_name: str
    vote: str  # "BUY", "SELL", "NEUTRAL"
    confidence: float
    weight: float
    reasoning: str = ""


@dataclass
class EnsembleResult:
    """Layer 3 output: consensus-checked setup."""
    scored_setup: ScoredSetup
    votes: list[EnsembleVote] = field(default_factory=list)
    buy_votes: float = 0.0
    sell_votes: float = 0.0
    neutral_votes: float = 0.0
    # P2 entry-direction fix (2026-06-04) — honest opposite-direction tally.
    # The legacy ``vote()`` polls every strategy with only the originator's
    # direction, and the per-strategy ``vote()`` methods are direction-
    # conditional confirmers (they return the asked direction or NEUTRAL,
    # never the opposite). So the opposing side is structurally zero even
    # when strong opposing signals exist (a bearish supertrend stays
    # NEUTRAL when asked about a Buy). When ``ensemble_two_sided_vote`` is
    # on, ``vote()`` runs a SECOND poll with the opposite direction and
    # records the real opposing weighted sum here so the brain reads an
    # honest Buy-vs-Sell contest. ``0.0`` / ``two_sided_active=False`` when
    # the flag is off (legacy, byte-identical). This field never alters the
    # consensus classification, the size, or the cache — it is surfaced to
    # the brain only, which is the direction decider.
    opposing_votes: float = 0.0
    two_sided_active: bool = False
    consensus_strength: str = ""  # "STRONG", "GOOD", "WEAK", "LEAN", "CONFLICT"
    consensus_direction: str = ""  # "BUY", "SELL", "NEUTRAL"
    passed: bool = True  # Always True now — consensus determines size, not eligibility
    size_multiplier: float = 1.0  # Consensus-based size: STRONG=1.0, GOOD=0.75, WEAK=0.3, CONFLICT=0.15
    # Layer 2 Defect 1 (2026-05-22) — per-cycle-per-symbol join key.
    # Generated by EnsembleVoter.vote as f"{cycle_iso}_{symbol}". Persisted
    # alongside each EnsembleVote row in the ensemble_votes table; the same
    # value lands on trade_intelligence.setup_id when a trade opens from
    # this setup so Layer 3 can JOIN votes to outcomes:
    #     SELECT ti.pnl_pct, COUNT(ev.strategy_name) AS vote_count,
    #            SUM(CASE WHEN ev.vote = ti.direction THEN 1 ELSE 0 END) AS supporting
    #     FROM trade_intelligence ti
    #     JOIN ensemble_votes ev ON ev.setup_id = ti.setup_id
    #     GROUP BY ti.id;
    setup_id: str = ""
    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "scored_setup": self.scored_setup.to_dict(),
            "buy_votes": round(self.buy_votes, 2),
            "sell_votes": round(self.sell_votes, 2),
            "neutral_votes": round(self.neutral_votes, 2),
            "opposing_votes": round(self.opposing_votes, 2),
            "two_sided_active": self.two_sided_active,
            "consensus_strength": self.consensus_strength,
            "consensus_direction": self.consensus_direction,
            "passed": self.passed,
            "vote_count": len(self.votes),
        }

    def vote_distribution_dict(self, *, reasoning_truncate: int = 140) -> dict:
        """Phase 2 of the 1D briefing rewrite — public per-strategy vote map.

        Returns the full vote distribution as
        ``{strategy_name: {"vote", "confidence", "weight", "reasoning"}}``.
        Today the votes list is logged once for STRONG consensus via
        ``STRAT_VOTE_TRACE`` and then discarded by ``StrategyWorker``;
        this accessor lets callers cache the full distribution per coin
        so the briefing-pipeline ranker, the State Labeler, and Claude's
        prompt can read individual strategy conviction (not just the
        STRONG/GOOD/LEAN aggregate).

        Args:
            reasoning_truncate: Cap on the reasoning string length so a
                verbose strategy explanation cannot bloat the cache. The
                truncated form keeps the head of the message — that's
                where strategies put the headline cause.

        Returns:
            Dict keyed by strategy name. When two votes share a name
            (defensive — should not happen in normal operation), the
            last-seen wins.
        """
        out: dict[str, dict] = {}
        for v in self.votes:
            reasoning = v.reasoning or ""
            if reasoning_truncate and len(reasoning) > reasoning_truncate:
                reasoning = reasoning[:reasoning_truncate]
            out[v.strategy_name] = {
                "vote": v.vote,
                "confidence": float(v.confidence),
                "weight": float(v.weight),
                "reasoning": reasoning,
            }
        return out


@dataclass
class TradeDecision:
    """Layer 4 output: Claude Brain's final decision."""
    ensemble_result: EnsembleResult
    action: str  # "execute", "skip", "modify"
    leverage: int
    stop_loss: float
    take_profit_1: float
    take_profit_2: Optional[float] = None
    take_profit_3: Optional[float] = None
    position_size_pct: float = 5.0
    reasoning: str = ""
    risk_notes: str = ""
    claude_cost_usd: float = 0.0
    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "action": self.action,
            "symbol": self.ensemble_result.scored_setup.raw_signal.symbol,
            "direction": self.ensemble_result.scored_setup.raw_signal.direction.value,
            "leverage": self.leverage,
            "stop_loss": self.stop_loss,
            "take_profit_1": self.take_profit_1,
            "take_profit_2": self.take_profit_2,
            "take_profit_3": self.take_profit_3,
            "position_size_pct": self.position_size_pct,
            "score": self.ensemble_result.scored_setup.total_score,
            "consensus": self.ensemble_result.consensus_strength,
            "reasoning": self.reasoning,
            "cost_usd": self.claude_cost_usd,
        }


@dataclass
class StrategyPerformance:
    """Tracks a strategy's live performance for ensemble weighting."""
    strategy_name: str
    total_trades: int = 0
    wins: int = 0
    losses: int = 0
    win_rate: float = 0.5
    avg_pnl_pct: float = 0.0
    avg_win_pct: float = 0.0
    avg_loss_pct: float = 0.0
    profit_factor: float = 1.0
    current_streak: int = 0
    ensemble_weight: float = 1.0
    enabled: bool = True
    last_trade_at: Optional[datetime] = None
    _total_win_pct: float = 0.0
    _total_loss_pct: float = 0.0

    def update(self, pnl_pct: float, was_win: bool) -> None:
        """Update performance after a trade."""
        self.total_trades += 1
        if was_win:
            self.wins += 1
            self.current_streak = max(1, self.current_streak + 1)
            self._total_win_pct += pnl_pct
            self.avg_win_pct = self._total_win_pct / self.wins if self.wins else 0
        else:
            self.losses += 1
            self.current_streak = min(-1, self.current_streak - 1)
            self._total_loss_pct += abs(pnl_pct)
            self.avg_loss_pct = self._total_loss_pct / self.losses if self.losses else 0

        self.win_rate = self.wins / self.total_trades if self.total_trades else 0.5
        total_pnl = self._total_win_pct - self._total_loss_pct
        self.avg_pnl_pct = total_pnl / self.total_trades if self.total_trades else 0
        self.profit_factor = (
            self._total_win_pct / self._total_loss_pct
            if self._total_loss_pct > 0
            else 99.0
        )
        self.last_trade_at = datetime.now(timezone.utc)
