"""Data models for the Strategy Factory."""

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


@dataclass
class DiscoveredPattern:
    """A pattern found by the discovery engine."""
    id: str
    pattern_type: str  # single_var, multi_var, sequential, cross_asset, temporal, news_reactive, micro
    description: str
    conditions: dict
    symbols: list[str] = field(default_factory=list)
    timeframe: str = "5"
    direction: str = "long"  # long, short, both

    # Statistics
    occurrences: int = 0
    wins: int = 0
    losses: int = 0
    win_rate: float = 0.0
    avg_profit_pct: float = 0.0
    avg_loss_pct: float = 0.0
    profit_factor: float = 0.0
    avg_hold_minutes: int = 0
    max_drawdown_pct: float = 0.0

    # Validation
    statistical_significance: float = 1.0  # p-value (lower = more significant)
    regime_consistency: dict = field(default_factory=dict)
    is_valid: bool = False

    # Metadata
    discovered_at: Optional[datetime] = None
    data_start_date: str = ""
    data_end_date: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "pattern_type": self.pattern_type,
            "description": self.description,
            "conditions": self.conditions,
            "symbols": self.symbols,
            "timeframe": self.timeframe,
            "direction": self.direction,
            "occurrences": self.occurrences,
            "wins": self.wins,
            "losses": self.losses,
            "win_rate": round(self.win_rate, 4),
            "avg_profit_pct": round(self.avg_profit_pct, 4),
            "avg_loss_pct": round(self.avg_loss_pct, 4),
            "profit_factor": round(self.profit_factor, 4),
            "statistical_significance": round(self.statistical_significance, 6),
            "is_valid": self.is_valid,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DiscoveredPattern":
        return cls(
            id=data["id"],
            pattern_type=data.get("pattern_type", ""),
            description=data.get("description", ""),
            conditions=data.get("conditions", {}),
            symbols=data.get("symbols", []),
            timeframe=data.get("timeframe", "5"),
            direction=data.get("direction", "long"),
            occurrences=data.get("occurrences", 0),
            wins=data.get("wins", 0),
            losses=data.get("losses", 0),
            win_rate=data.get("win_rate", 0.0),
            avg_profit_pct=data.get("avg_profit_pct", 0.0),
            avg_loss_pct=data.get("avg_loss_pct", 0.0),
            profit_factor=data.get("profit_factor", 0.0),
            statistical_significance=data.get("statistical_significance", 1.0),
            regime_consistency=data.get("regime_consistency", {}),
            is_valid=data.get("is_valid", False),
        )


@dataclass
class GeneratedStrategy:
    """A strategy generated by Claude from a discovered pattern."""
    id: str
    pattern_id: str
    strategy_name: str
    code: str

    claude_model: str = ""
    generation_prompt_hash: str = ""
    generation_cost_usd: float = 0.0
    generation_attempts: int = 1

    syntax_valid: bool = False
    safety_valid: bool = False
    interface_valid: bool = False
    validation_errors: list[str] = field(default_factory=list)

    status: str = "generated"  # generated → validated → backtesting → trial → promoted → demoted → killed

    generated_at: Optional[datetime] = None
    validated_at: Optional[datetime] = None

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "pattern_id": self.pattern_id,
            "strategy_name": self.strategy_name,
            "status": self.status,
            "syntax_valid": self.syntax_valid,
            "safety_valid": self.safety_valid,
            "interface_valid": self.interface_valid,
            "validation_errors": self.validation_errors,
            "generation_cost_usd": self.generation_cost_usd,
            "generation_attempts": self.generation_attempts,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "GeneratedStrategy":
        return cls(
            id=data["id"],
            pattern_id=data.get("pattern_id", ""),
            strategy_name=data.get("strategy_name", ""),
            code=data.get("code", ""),
            status=data.get("status", "generated"),
            syntax_valid=data.get("syntax_valid", False),
            safety_valid=data.get("safety_valid", False),
            interface_valid=data.get("interface_valid", False),
            validation_errors=data.get("validation_errors", []),
            generation_cost_usd=data.get("generation_cost_usd", 0.0),
        )


@dataclass
class PatternOccurrence:
    """Records each time a pattern fires in live data."""
    pattern_id: str
    symbol: str
    timestamp: datetime
    conditions_snapshot: dict = field(default_factory=dict)
    price_at_detection: float = 0.0
    price_after_1h: Optional[float] = None
    price_after_4h: Optional[float] = None
    price_after_24h: Optional[float] = None
    outcome: Optional[str] = None  # win, loss, pending
    pnl_pct: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "pattern_id": self.pattern_id,
            "symbol": self.symbol,
            "timestamp": self.timestamp.isoformat() if self.timestamp else "",
            "price_at_detection": self.price_at_detection,
            "outcome": self.outcome,
            "pnl_pct": self.pnl_pct,
        }


@dataclass
class EmergingPattern:
    """A pattern appearing frequently in recent data but not yet cataloged."""
    description: str
    conditions: dict
    recent_occurrences: int = 0
    recent_win_rate: float = 0.0
    urgency: str = "low"  # low, medium, high, critical
    detected_at: Optional[datetime] = None

    def to_dict(self) -> dict:
        return {
            "description": self.description,
            "conditions": self.conditions,
            "recent_occurrences": self.recent_occurrences,
            "recent_win_rate": round(self.recent_win_rate, 4),
            "urgency": self.urgency,
        }
